name: Build Bicep-ARM template

on:
  push:
    paths:
      - 'main.bicep'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Bicep build
        run: |
          curl -Lo bicepinstall https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicepinstall
          sudo mv ./bicepinstall /usr/local/bin/bicep
          bicep --help
      
      - name: Run Bicep build
        run: |
          bicep build main.bicep
          ls -l *.json
          
      - uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: Update Bicep-ARM template
          add: main.json
